# Generated by Django 5.2.1 on 2025-05-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitmileapi', '0002_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='classroom_name',
            field=models.CharField(default='ClassroomNamePlaceholder', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='school',
            unique_together={('name', 'municipality')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('full_name', 'classroom')},
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('full_name', 'school')},
        ),
    ]
