# Generated by Django 5.2.1 on 2025-06-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitmileapi', '0003_classroom_classroom_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='school',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='school',
            name='region',
            field=models.CharField(default='RegionPlaceholder', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='school',
            unique_together={('name', 'municipality', 'region')},
        ),
    ]
