# Generated by Django 5.2.1 on 2025-06-29 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitmileapi', '0004_alter_school_unique_together_school_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnregisteredSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('municipality', models.CharField(max_length=255)),
                ('region', models.CharField(default='RegionPlaceholder', max_length=255)),
                ('contact_person_name', models.CharField(max_length=255)),
                ('contact_person_email', models.EmailField(max_length=254)),
            ],
            options={
                'unique_together': {('name', 'municipality', 'region')},
            },
        ),
        migrations.CreateModel(
            name='UnregisteredTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unregistered_teachers', to='digitmileapi.school')),
            ],
        ),
    ]
