# Generated by Django 5.2.1 on 2025-06-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitmileapi', '0005_unregisteredschool_unregisteredteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unregisteredschool',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unregisteredschool',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
