# Generated by Django 5.2.8 on 2025-12-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitmileapi', '0006_school_latitude_school_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstatistics',
            name='correct_moves',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runstatistics',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runstatistics',
            name='place',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runstatistics',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runstatistics',
            name='time_elapsed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runstatistics',
            name='wrong_moves',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
