# Generated by Django 5.2.8 on 2025-12-27 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitmileapi', '0007_runstatistics_correct_moves_runstatistics_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSchoolAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_at_school', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UnregisteredSchool',
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_person_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_person_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_person_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='director_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='director_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='google_maps_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='school',
            name='school_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='school_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='noemail@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='years_teaching',
            field=models.IntegerField(blank=True, help_text='Total years of teaching experience', null=True),
        ),
        migrations.AddField(
            model_name='teacherschoolassignment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='digitmileapi.school'),
        ),
        migrations.AddField(
            model_name='teacherschoolassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_assignments', to='digitmileapi.teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='schools',
            field=models.ManyToManyField(related_name='teachers', through='digitmileapi.TeacherSchoolAssignment', to='digitmileapi.school'),
        ),
        migrations.DeleteModel(
            name='UnregisteredTeacher',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='school',
        ),
        migrations.AlterUniqueTogether(
            name='teacherschoolassignment',
            unique_together={('teacher', 'school')},
        ),
    ]
