# Generated by Django 5.2.8 on 2025-12-27 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitmileapi', '0008_teacherschoolassignment_delete_unregisteredschool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(blank=True, help_text='The school where this classroom is located', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='digitmileapi.school'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('classroom_key', 'school')},
        ),
    ]
