# Generated by Django 5.2.8 on 2025-12-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitmileapi', '0009_classroom_school_alter_classroom_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='grade',
            field=models.IntegerField(blank=True, help_text='Grade level of the classroom', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Student date of birth', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.IntegerField(blank=True, help_text='Student grade level', null=True),
        ),
    ]
