"""
Django settings for digitmile project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

from django.conf.global_settings import APPEND_SLASH
from dotenv import load_dotenv
load_dotenv() # This will load variables from a .env file in your project root

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)bpw(3%nq@n54q!qfc=stwjs8^-2nar(%=s*@-f9dbm4__0h@s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

SERVER_IP = os.getenv('SERVER_IP')
ALLOWED_HOSTS = [SERVER_IP, '127.0.0.1', 'localhost']

APPEND_SLASH=False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'digitmileapi'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'digitmile.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'digitmile.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# print(os.getenv('DB_NAME'))
# print(os.getenv('DB_USER'))
# print(os.getenv('DB_PASS'))
# print(os.getenv('DB_HOST'))
# print(os.getenv('DB_PORT'))
# PASTE THIS ENTIRE BLOCK:
db_port_env = os.getenv('DB_PORT')
processed_db_port = ''  # Default to empty string, telling Django not to specify a port to psycopg2

if db_port_env and db_port_env.strip().isdigit():
    # If DB_PORT is set and is a number, use it as an integer
    processed_db_port = int(db_port_env.strip())
elif not db_port_env:
    # If DB_PORT is not set in .env at all, default to 5432 (integer)
    processed_db_port = 5432
# If DB_PORT is set but is not a simple number (e.g., an empty string from .env, or non-numeric),
# processed_db_port remains '', which is fine for Django's database wrapper.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASS'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': processed_db_port, # Use the explicitly processed port
    }
}
# END OF BLOCK TO PASTE

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
